Chris g/snitch conversion
xdslproject/xdsl pull request #1109
Opened 2023-06-09 15:22 UTC by KGrykiel

@JosseVanDelm I made classes for all the snitch operations without any arguments as well as a test for each like we discussed. let me know if I'm on the right track with this.

2023-06-09 17:20 UTC, superlopuh commented on .pre-commit-config.yaml
what's the diff here?

2023-06-09 17:22 UTC, KGrykiel commented on .pre-commit-config.yaml
nothing as far as I'm aware, but it wouldn't let me commit otherwise for some reason

2023-06-09 17:23 UTC, superlopuh commented on .pre-commit-config.yaml
I'll try removing this locally and see what happens, will push if it works

2023-06-09 17:25 UTC, superlopuh commented on .pre-commit-config.yaml
![Screenshot 2023-06-09 at 18 24 37](https://github.com/xdslproject/xdsl/assets/910320/1ac1a3dd-4929-4d21-9b56-191050e01c3e)
Looks like you opened it in a rogue editor that inserted a bunch of carriage returns!

2023-06-09 17:26 UTC, superlopuh commented on .pre-commit-config.yaml
pushed revert

2023-06-09 17:28 UTC, KGrykiel commented on .pre-commit-config.yaml
huh, bizarre

2023-06-12 10:59 UTC, AntonLydike approved these changes

2023-06-13 09:02 UTC, nazavode requested changes
With a bit of documentation this would be perfect, thanks!

2023-06-13 09:02 UTC, nazavode commented on xdsl/dialects/snitch_runtime.py
> +    """ """
Please add some docs, these are quite important to understand the overall cluster topology.

2023-06-14 13:55 UTC, JosseVanDelm requested changes
@nazavode Could you check with these added docs, they were not properly documented upstream, so I had to look into example code myself...?
it seems that not all functions actually do what they "promise" right now...

2023-06-20 10:18 UTC, nazavode commented
@JosseVanDelm I had to go through the examples/runtime code too and I think your suggested changes are spot on, thanks. @KGrykiel I think c6335fa slipped in from #1157.

2023-06-22 14:21 UTC, JosseVanDelm commented on .pre-commit-config.yaml
Adding this thread here for future reference, since this seemed to do the trick!:
https://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git

2023-06-22 14:36 UTC, JosseVanDelm approved these changes

2023-06-22 16:48 UTC, superlopuh approved these changes

2023-06-23 10:13 UTC, merged