dialects: (linalg) Add linalg dialect
xdslproject/xdsl pull request #1215
Opened 2023-06-29 15:56 UTC by Groverkss

2023-06-29 16:01 UTC, superlopuh requested changes

2023-06-29 16:37 UTC, webmiche commented on tests/dialects/test.mlir
This is not actually executed, right?

2023-07-02 01:02 UTC, Groverkss commented on tests/dialects/test.mlir
Accidentally added this file. Fixed now.

2023-07-02 08:32 UTC, superlopuh approved these changes

2023-07-03 07:05 UTC, webmiche approved these changes
LGTM now :+1: 

Did you see [this PR](https://github.com/xdslproject/xdsl/pull/62/files) btw?

2023-07-03 09:49 UTC, merged