Defined cmath with the IRDL from xDSL + added tests
xdslproject/xdsl pull request #127
Opened 2022-06-24 15:20 UTC by purvi-H

Wrote and registered the cmath dialect + tested it.

2022-06-24 17:48 UTC, tobiasgrosser reviewed
Very cool. Thank you for this PR.

2022-06-24 17:48 UTC, tobiasgrosser commented on tests/filecheck/.lit_test_times.txt
> +9.212685e-02 cmath.xdsl
Does this need to be added?

2022-06-26 23:38 UTC, math-fehr requested changes
Could you fix the comments we sent?
Also, could you format your files using yapf, so it passes the CI?

2022-06-26 23:38 UTC, math-fehr commented on src/xdsl/dialects/cmath.py
> +from xdsl.dialects.irdl import *
Can you remove the unused imports (irdl, func, and arith)?

2022-06-26 23:38 UTC, math-fehr commented on src/xdsl/dialects/cmath.py
> +class Cmath:
Could you rename it to `CMath`?

2022-06-26 23:38 UTC, math-fehr commented on src/xdsl/dialects/cmath.py
> +    data: ParameterDef[Float64Type | Float32Type]
Can you remove this line?

2022-06-26 23:38 UTC, math-fehr commented on tests/filecheck/cmath.xdsl
> +// RUN: xdsl-opt %s | xdsl-opt | filecheck %s
So this file is the cmath dialect, but written as a program with the IRDL dialect.
Could you remove this file for a subsequent PR? And instead have a file that test CMath.
So for instance something like https://github.com/opencompl/dyn-dialect/blob/main/test/Dyn/test-cmath.mlir, but using an xDSL syntax

2022-06-30 13:16 UTC, merged