dialect: Deprecating `.get` in llvm dialect
xdslproject/xdsl pull request #1349
Opened 2023-07-26 13:42 UTC by ShaolunWang

Making respective changes from .get to __init__ in mpi lowering and llvm/mpi tests

2023-07-26 13:56 UTC, AntonLydike requested changes
I think this is much easier to review once you make `get` just call `__inti__`... Otherwise it looks good! Thanks!

2023-07-26 13:56 UTC, AntonLydike commented on xdsl/dialects/llvm.py
>          ptr: SSAValue | Operation,
Can you make this call `__init__` instead of duplicating code?

2023-07-26 13:56 UTC, AntonLydike commented on xdsl/dialects/llvm.py
>          size: SSAValue | Operation,
Same here, would be nice to make this just pass everything to `__init__`...

2023-07-26 15:37 UTC, kingiler approved these changes

2023-07-27 08:20 UTC, AntonLydike approved these changes
Perfect! Thanks!

2023-07-27 08:20 UTC, merged