core: Rename register_* with load_*
xdslproject/xdsl pull request #1663
Opened 2023-10-13 00:05 UTC by math-fehr

This PR renames `register_*` with `load_*`.
`load_*` is the naming used by MLIR, so it makes sense to go there.
Also, I would like to add a `register_*` methods, as in #1116

2023-10-13 00:47 UTC, superlopuh requested changes
couple of stray diffs

2023-10-13 00:47 UTC, superlopuh commented on docs/irdl.ipynb
> +   "version": "3.10.12"
.

2023-10-13 00:47 UTC, superlopuh commented on docs/tutorial.ipynb
> +    "cells": [
😱

2023-10-16 16:32 UTC, math-fehr commented
> couple of stray diffs

Oops, that should be fixed now, thanks!

2023-10-16 19:35 UTC, superlopuh approved these changes

2023-10-17 08:12 UTC, webmiche approved these changes

2023-10-17 23:53 UTC, merged