interactive: added label to display selected queries to user (5/7)
xdslproject/xdsl pull request #1773
Opened 2023-11-10 14:36 UTC by dshaaban01

added label to display selected queries to user.

![image](https://github.com/xdslproject/xdsl/assets/144673861/120dcdfa-62e6-4e3d-8cb7-2c160f2e3853)

2023-11-10 14:37 UTC, superlopuh commented on tests/interactive/test_app.py
> +        pilot: Pilot[None] = pilot
don't need this any more

2023-11-10 14:37 UTC, superlopuh commented on xdsl/interactive/app.py
> +    current_module = reactive[ModuleOp | Exception | None](None)
isn't this in a different PR?

2023-11-11 21:20 UTC, superlopuh requested changes
It feels a little off for the borders to be unaligned above and below, could you please make them line up?

2023-11-11 21:20 UTC, superlopuh commented on xdsl/interactive/app.tcss
> +    # grid-columns: 75% 25%;
please remove commented line

2023-11-13 09:15 UTC, webmiche commented
I keep getting confused with all of these PRs and how they are ordered. Could you add an index to the PR title? Something like `interactive: (3/8) ...` 8or `interactive: (3/?) ...` if you don't know how many there are.

2023-11-13 09:18 UTC, webmiche commented
Classic, supervisors giving conflicting advice :wink:

2023-11-13 13:47 UTC, superlopuh commented
Please merge main and I'll take a look

2023-11-13 13:53 UTC, superlopuh requested changes
looking good, just want to avoid the same class variable situation with the new setter

2023-11-13 13:53 UTC, superlopuh commented on xdsl/interactive/app.py
> +    """Display's user selected passes"""
```suggestion
    """Display's user selected passes."""
```

2023-11-13 13:53 UTC, superlopuh commented on xdsl/interactive/app.py
> +    passes_selection_list: SelectionList[type[ModulePass]] = SelectionList(
please move to init

2023-11-13 13:53 UTC, superlopuh commented on xdsl/interactive/app.py
> +    passes_selection_list: SelectionList[type[ModulePass]] = SelectionList(
also please move variable declarations above init

2023-11-13 14:12 UTC, superlopuh requested changes

2023-11-13 14:12 UTC, superlopuh commented on xdsl/interactive/app.py
> +        self.passes_selection_list: SelectionList[type[ModulePass]] = SelectionList(
```suggestion
        self.selected_query_label = Label("", id="selected_passes_label")
```

2023-11-13 14:12 UTC, superlopuh commented on xdsl/interactive/app.py
> +    selected_query_label = Label("", id="selected_passes_label")
```suggestion
    selected_query_label: Label
```

2023-11-13 14:32 UTC, superlopuh approved these changes

2023-11-13 14:34 UTC, merged