interactive: change to ListView (1/7)
xdslproject/xdsl pull request #1788
Opened 2023-11-15 15:19 UTC by dshaaban01

Instead of doing a selection list, I have changed it to a list view. This allows us to apply the SAME pass multiple times instead of only being allowed to apply one pass type one time. This is also useful to introduce the condense button functionality (which was difficult to cleanly implement under the SelectionList set up).

![image](https://github.com/xdslproject/xdsl/assets/144673861/cee67cd7-d7f0-4fac-957a-ae6eba26aa8c)

2023-11-15 15:20 UTC, compor commented
Screenshot or it didn't happen :)

2023-11-15 16:21 UTC, superlopuh commented on tests/interactive/test_app.py
> -
feels like a shame to remove the test entirely. Let's keep as much of the functionality covered as makes sense. For example, we can still test that the outputs are updated in the way that we expect when the model object changes, even if we don't test the user action for now.

2023-11-15 16:31 UTC, superlopuh requested changes

2023-11-17 13:17 UTC, superlopuh approved these changes

2023-11-17 13:29 UTC, superlopuh commented
Looks like a bug in the CI, makes sense since PRs on top of this one pass, it happens sometimes, I just restarted it

2023-11-17 13:42 UTC, merged