interactive: preload initial example(6/7)
xdslproject/xdsl pull request #1801
Opened 2023-11-16 18:06 UTC by dshaaban01

preload initial example into gui so users can gain a quicker understanding + theme changes to make sure that text area is visible to everyone (@tobiasgrosser had some issues seeing the text in the text area as the background colour+text colour of TextArea's were similar ). 

Light Mode: 
![image](https://github.com/xdslproject/xdsl/assets/144673861/5dae1206-d3fd-492b-897d-4fdaee98d312)

Dark Mode:
![image](https://github.com/xdslproject/xdsl/assets/144673861/2f971166-225c-45ac-839a-6578313a2a75)

2023-11-17 11:57 UTC, compor approved these changes
LGTM, an external config file for the preloaded text, the themes, etc might be something to consider in the future.

2023-11-17 13:31 UTC, superlopuh requested changes

2023-11-17 13:31 UTC, superlopuh commented on xdsl/interactive/app.py
> +        self.input_text_area.theme = "vscode_dark"
This is unrelated to the preloading of the text, could you please split out the two PRs? They also don't seem like they would need to be in a stack as they don't functionally depend on anything not in main

2023-11-17 13:46 UTC, superlopuh commented on xdsl/interactive/app.py
> +        self.input_text_area.theme = "vscode_dark"
Yes

2023-11-18 11:18 UTC, superlopuh requested changes

2023-11-18 11:18 UTC, superlopuh commented on xdsl/interactive/app.py
> +            """func.func @hello(%n : index) -> index {
Can you please move this out to an UPPER_CAMEL_CASE constant at the level of the file? Maybe called `INITIAL_IR_TEXT`, or something like that?

2023-11-20 09:37 UTC, webmiche approved these changes

2023-11-20 14:14 UTC, closed without merging