(bug): Teach densearray parse function to accept IndexType
xdslproject/xdsl pull request #3247
Opened 2024-10-06 09:01 UTC by vinayakdsci

Resolves https://github.com/xdslproject/xdsl/issues/3154.

This patch eases the type constraints in `_parse_builtin_densearray_attr()` to include `IndexType`.
Also adds a test for the change.

2024-10-06 11:28 UTC, vinayakdsci commented
cc @superlopuh @watermelonwolverine.

2024-10-06 21:20 UTC, superlopuh requested changes
```
❯ cat hello.mlir
%x9 = "arith.constant"() {"value" = 0 : i64, "test" = array<index: 2, 3, 4>} : () -> i64
❯ mlir-opt hello.mlir
Assertion failed: (isIntOrFloat() && "only integers and floats have a bitwidth"), function getIntOrFloatBitWidth, file Types.cpp, line 124.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
...
```

MLIR segfaults with this, I'm not sure we should support it if MLIR doesn't. This makes sense to me, as dense is for fixed-bitwidth dense data, and index is platform-dependent.

2024-10-08 08:05 UTC, vinayakdsci commented
@superlopuh hi, sorry for the late reply. I understand your point, and agree with it. But this would also mean that the type constraints on `DenseArrayBase.create_dense_int_or_index` should then be tightened to not accept an Index type, if I understand the situation correctly?

2024-10-08 09:10 UTC, superlopuh commented
It seems like it, that would be a great change to make if you have the bandwidth to implement it

2024-10-08 09:17 UTC, vinayakdsci commented
> It seems like it, that would be a great change to make if you have the bandwidth to implement it

Sure can!  Should I also rename the function to remove the `index` part?

2024-10-08 09:45 UTC, vinayakdsci commented
> Sure can! Should I also rename the function to remove the `index` part?

OK, I have renamed the function to remove int (in a new PR). This is so because otherwise the function's name would be misleading, as it mentions IndexType, but does not accept it.

2024-10-08 09:55 UTC, vinayakdsci commented
This PR has errors in its approach, which are fixed by https://github.com/xdslproject/xdsl/pull/3258. Therefore, closing this PR to follow up on the latter.

2024-10-08 09:55 UTC, closed without merging