xDSL: Add structural equivalence comparison for IRNode
xdslproject/xdsl pull request #325
Opened 2023-01-12 14:26 UTC by martin-luecke

This PR adds a function to check whether two instances of `IRNode` are structurally equivalent, i.e. they share all relevant fields but don't have to be the same object.

2023-01-12 14:50 UTC, webmiche requested changes
Just to mention it here: I don't really like that there is now a dependency from `test_ir` to the dialects. At the same time, I don't actually know how to fix this. I am starting to want a testing dialect even more though...

2023-01-12 14:50 UTC, webmiche commented on xdsl/ir.py
> +        for idx, region in enumerate(self.regions):
Maybe use all() here?

2023-01-12 14:50 UTC, webmiche commented on xdsl/ir.py
> +                return False
all() as well here

2023-01-12 14:50 UTC, webmiche commented on xdsl/ir.py
> +            context[result] = other.results[idx]
Why enumerate? Why not zip this time?

2023-01-12 16:43 UTC, martin-luecke commented on xdsl/ir.py
> +                return False
:+1:

2023-01-12 16:43 UTC, martin-luecke commented on xdsl/ir.py
> +            context: Optional[dict[IRNode, IRNode]] = None) -> bool:
:+1:

2023-01-12 16:43 UTC, martin-luecke commented on xdsl/ir.py
> +            context[result] = other.results[idx]
:+1:

2023-01-12 16:51 UTC, webmiche requested changes
I think there are some lines in the code that are not covered yet, which should be possible. In particular, `is_structurally_equivalent` is never called on Regions and Blocks. Could you add that?

2023-01-12 16:51 UTC, webmiche commented on xdsl/ir.py
> +        for arg, other_arg in zip(self.args, other.args):
I think there might be another all() possible here.

2023-01-12 16:51 UTC, webmiche commented on xdsl/ir.py
> +        return True
newline?

2023-01-13 10:41 UTC, webmiche approved these changes

2023-01-13 10:41 UTC, merged