WIP: QSSA encoding
xdslproject/xdsl pull request #331
Opened 2023-01-13 10:12 UTC by pingshiyu

As an example dialect showcasing xDSL features which might be useful for other learning xDSL, and as a way for myself to get familiar with xDSL, I've been implementing the QSSA dialect (https://dl.acm.org/doi/pdf/10.1145/3497776.3517772) within xDSL as a first project.

It's still a WIP and not all of the features are faithfully implemented yet, however I'm opening this PR as a draft to get some feedback on the implementation so far. I'm still in learning stages of xDSL/MLIR so suggestions and better / cleaner ways to do things are very welcome!

2023-01-15 23:36 UTC, math-fehr commented
Nice! This looks quite nice, I'll take a deeper look tomorrow if you want (mostly on the dialect definition, I'm not really familiar with the domain itself).

For Traits in xDSL, you can directly use class inheritance. Something like:
```
class MyOp(Operation, Pure):
   ...
```
This essentially gives traits and interfaces for free from Python. You can call the functions directly, and use `isinstance` to check if an operation satisfy a trait or not.

I don't think you can define dynamic tensors in MLIR, or if you could, this is definitely not implemented in xDSL. I'm not sure how this would work though, since when lowering to LLVM, we would need to know the element type size to be able to access elements in the tensor.

2023-01-16 10:43 UTC, pingshiyu commented
Thank you very much Mathieu for your comments! It'd be very appreciate if you could take a closer look at the dialect definitions too, if possible!

Thank you also for your thoughts on implementing traits & dynamic arrays! I'll have more of a think about the dynamic arrays and will keep traits in mind for future :)

2023-01-23 09:20 UTC, webmiche reviewed
LGTM overall. I don't quite get why you are naming your builder `apply`, but I guess you are thinking of this differently than I do (maybe in terms of functons instead of operations?). Also, I would add some lit tests, I feel these are nicer to look at (at least that is how I think about IRs).

2023-01-23 23:48 UTC, pingshiyu commented
@webmiche thank you for looking through and for your feedback! I will look into the lit tests :)

2023-02-05 16:52 UTC, superlopuh requested changes
Code mostly look good, marking as request changes until no longer WIP

2023-02-05 16:52 UTC, superlopuh commented on xdsl/dialects/qssa.py
> +class Angle(Data[float]):
what's the unit?

2023-07-26 13:18 UTC, AntonLydike commented
Is this PR still active?

2023-07-26 14:10 UTC, closed without merging

2023-07-26 14:11 UTC, pingshiyu commented
> 

not working on this anymore, will go ahead and close.