Switch to using entry_points for xdsl-opt script.
xdslproject/xdsl pull request #475
Opened 2023-02-25 22:57 UTC by KarelPeeters

This makes the script automatically work on all platforms, the previous method only worked on linux.

2023-02-26 02:25 UTC, PapyChacal requested changes
Thanks for that!
Mh, but after that, from Linux, I can't just `xdsl/tools/xdsl-opt` from the CLI :thinking: 
Do you think you can find a way to do both?

```python3
#!/usr/bin/env python3

from xdsl.xdsl_opt_main import xDSLOptMain


def main():
    xDSLOptMain().run()


if __name__ == "__main__":
    main()
```
Seems to work alright on Linux. I would also like to keep the name without the extension. Do you need it from windows?

2023-02-26 11:18 UTC, KarelPeeters commented
Ah, I figured the typical use case is to `pip install -e` the repository, in which case this changes nothing on Linux: the installation process still ends up putting an executable called `xdsl-opt` in the Python Scripts folder.

Otherwise we can just keep the old `xdsl/tools/xdsl-opt` script around in the repository exactly like it was. The `entry_points` method _does_ require the `.py` extension.

Let me know your thoughts, I can easily undo the removal in this PR!

2023-02-26 16:23 UTC, AntonLydike commented
This is cool! I think we should look into fixing the filecheck CI to work with this. Otherwise I'm all for easy multi-platform wins!

2023-02-26 17:21 UTC, KarelPeeters commented
I've restored the old script, that should both fix CI and get some backwards compatibility back.

2023-02-27 08:59 UTC, webmiche approved these changes
LGTM, and works on my (linux-based) machine.

2023-02-27 10:37 UTC, PapyChacal approved these changes
Good idea keeping the current one, didn't think of that :)

2023-02-27 20:44 UTC, KarelPeeters commented
I think I've fixed the CI formatting issue.

2023-02-28 06:42 UTC, merged