frontend: Add README with a toy example
xdslproject/xdsl pull request #793
Opened 2023-04-27 08:37 UTC by georgemitenkov

There were some questions on zulip about frontend, and I realised that I never moved the old README here. This PR starts the migration by adding a simple toy example.

Next, the plan is to talk about architecture, partial evaluation of constants using `Const[i32]`, and desymrefier.

P.S. Toy example should be less basic, but I have to move more things from `frontend` branch prior to doing so.

2023-04-27 08:52 UTC, georgebisbas requested changes

2023-04-27 08:52 UTC, georgebisbas commented on xdsl/frontend/README.md
> +This document briefly describes the front-end framework. Please not that this is
some typos here and there

2023-04-27 18:58 UTC, superlopuh approved these changes

2023-04-28 12:30 UTC, math-fehr approved these changes
:+1:

2023-05-01 20:24 UTC, superlopuh commented
@georgebisbas , could you please re-review?

2023-05-02 08:59 UTC, merged