tests: Move xdsl-opt tests to MLIR syntax
xdslproject/xdsl pull request #804
Opened 2023-04-28 15:32 UTC by math-fehr

2023-04-28 17:24 UTC, georgebisbas requested changes

2023-04-28 17:24 UTC, georgebisbas commented on tests/xdsl_opt/empty_program.wrong
'.wrong' ?

2023-04-28 18:19 UTC, math-fehr commented on tests/xdsl_opt/empty_program.wrong
This was already there, so I didn't changed it.

2023-04-28 18:22 UTC, math-fehr commented on tests/xdsl_opt/empty_program.wrong
I feel that if we want to do this, we should do this in another PR rather than in this one, otherwise we are mixing stuff in PRs.

2023-04-28 19:25 UTC, webmiche approved these changes
Not sure, I personally don't really like these tests in general, sepecifically since they only execute code paths that are hit by other tests already, but not properly recorded by the coverage package (AFAIR).

I would be okay with just dropping them totally and not move the syntax over.

2023-04-28 19:39 UTC, math-fehr commented on tests/xdsl_opt/empty_program.wrong
Looking at the test, it indicates that the extension is wrong, so we should keep it as is I think.

2023-04-29 09:58 UTC, superlopuh approved these changes

2023-04-29 17:03 UTC, georgebisbas approved these changes

2023-04-29 17:20 UTC, merged