dialects: Add tests for stencil.IndexAttr
xdslproject/xdsl pull request #909
Opened 2023-05-06 17:00 UTC by meshtag

This PR intends to add tests for `stencil.IndexAttr`. It should eventually help in bringing this attribute out of the experimental directory along with `stenil.FieldType`. Will do that in a separate commit.

2023-05-06 17:17 UTC, superlopuh commented on tests/dialects/test_stencil.py
> +def test_create_index_attr_from_int_list(indices: List[int]):
```suggestion
def test_create_index_attr_from_int_list(indices: list[int]):
```

2023-05-06 17:17 UTC, superlopuh requested changes
could you please migrate to `list` from `List`?

2023-05-06 17:17 UTC, superlopuh commented on tests/dialects/test_stencil.py
> +def test_index_attr_size_from_bounds(indices1: List[int], indices2: List[int]):
```suggestion
def test_index_attr_size_from_bounds(indices1: list[int], indices2: list[int]):
```

2023-05-06 17:17 UTC, superlopuh commented on tests/dialects/test_stencil.py
> +def test_index_attr_size_from_bounds(indices1: List[int], indices2: List[int]):
And below

2023-05-06 21:49 UTC, math-fehr approved these changes
Nice!

2023-05-07 09:22 UTC, tobiasgrosser approved these changes
Nice.

2023-05-07 10:39 UTC, superlopuh approved these changes

2023-05-07 10:39 UTC, superlopuh commented
ty

2023-05-07 10:39 UTC, merged