dialects: dialects: add snitch → riscv lowering
xdslproject/xdsl pull request #919
Opened 2023-05-07 10:58 UTC by nazavode

This PR adds lowering of `snitch` operations to `riscv` operations that represent the correct instruction sequences needed to actually configure streaming on the actual hw.

2023-05-07 11:02 UTC, nazavode commented
Note: this is larger than the suggested patch size, a reasonable split would be one PR for the `riscv.scfgw` op and another for the actual lowering.

2023-05-07 11:31 UTC, superlopuh commented on xdsl/dialects/snitch.py
> +    Dimensions: int = 4
Is this a class or instance variable?

2023-05-07 11:39 UTC, superlopuh requested changes

2023-05-07 11:39 UTC, superlopuh commented on xdsl/transforms/lower_snitch.py
> +    Bound: int
```suggestion
    bound: int
```
and below

2023-05-07 12:57 UTC, superlopuh approved these changes

2023-05-12 04:48 UTC, tobiasgrosser approved these changes
This LGTM

2023-05-12 08:25 UTC, merged