WIP: hackathon: dialects:  improvements to memref dialect for explicit cache mgmt
xdslproject/xdsl pull request #926
Opened 2023-05-08 09:17 UTC by JosseVanDelm

Trying out the stuff we try to propose in an RFC to improve the memref dialect.

Things we are trying/will try out
- Make num_elements an optional attribute if shapes of attributes match exactly
- Use subviews as arguments of dma_start instead of index/stride params
- Move dma_start to async dialect, to replace tag with token?

2023-05-12 11:11 UTC, math-fehr approved these changes
:+1:

2023-05-12 13:37 UTC, superlopuh requested changes
Is this still wip?

2023-05-12 13:37 UTC, superlopuh commented on xdsl/dialects/memref.py
> +        # num_elms_val = [] if num_elements is None else [num_elements]
commented code

2023-05-19 10:55 UTC, JosseVanDelm commented
I'm not working on this anymore so I'll close this one for now.
I'm expecting this to become more relevant later

2023-05-19 10:55 UTC, closed without merging